In [ ]:
# This is how we import a library such as Pandas. Pandas contains many built-in functions.
# These functions have already been created by developers and are readily available for use in our daily tasks.
# We shorten the name "pandas" to "pd" using the keyword "as" for convenience.
# Pandas is mainly used to work with tabular data, such as data stored in spreadsheets and databases.

In [6]:
import pandas as pd

In [2]:
# We are loading the data file saved in the same folder as the Python project.
# The file path must be correct, and the filename must exactly match the name of the data file.
# Here, we create a variable called "dataset" and use the Pandas read_csv() function to read the data.
# When this code is executed, the entire CSV dataset is loaded into the "dataset" variable.

In [7]:
dataset=pd.read_csv("Salary_Data.csv")

In [ ]:
# After creating and assigning a value to a variable, it is good practice to test it to ensure that the assignment was successful.

In [8]:
dataset

    YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [3]:
# The next step in model creation/learning is to split the dataset into input and output variables.
# Here, we assign the input column, "YearsExperience", to a variable called "independent".
# Since the original data is already stored in the variable "dataset", we select the "YearsExperience" column from it.

In [9]:
independent=dataset[["YearsExperience"]]

In [ ]:
# It is good practice to test variable to ensure that the assignment was successful.

In [10]:
independent

    YearsExperience
0               1.1
1               1.3
2               1.5
3               2.0
4               2.2
5               2.9
6               3.0
7               3.2
8               3.2
9               3.7
10              3.9
11              4.0
12              4.0
13              4.1
14              4.5
15              4.9
16              5.1
17              5.3
18              5.9
19              6.0
20              6.8
21              7.1
22              7.9
23              8.2
24              8.7
25              9.0
26              9.5
27              9.6
28             10.3
29             10.5

In [ ]:
# Here, we assign the output column, "Salary", to a variable called "dependent".
# Since the original data is already stored in the variable "dataset", we select the "Salary" column from it.

In [11]:
dependent=dataset[["Salary"]]

In [ ]:
# It is good practice to test the variable to ensure that the assignment was successful.

In [9]:
dependent

      Salary
0    39343.0
1    46205.0
2    37731.0
3    43525.0
4    39891.0
5    56642.0
6    60150.0
7    54445.0
8    64445.0
9    57189.0
10   63218.0
11   55794.0
12   56957.0
13   57081.0
14   61111.0
15   67938.0
16   66029.0
17   83088.0
18   81363.0
19   93940.0
20   91738.0
21   98273.0
22  101302.0
23  113812.0
24  109431.0
25  105582.0
26  116969.0
27  112635.0
28  122391.0
29  121872.0

In [ ]:
# # The next step in model creation/learning is "Split train and test".

In [ ]:
# Similar to Pandas, we use the "sklearn" library for this task.
# However, instead of importing the entire library, we import only the required function.
# Here, we import the train_test_split() function from sklearn's model_selection module.
# This function is used to divide the independent and dependent variables into training and testing datasets.

In [ ]:
# The train_test_split() function returns four separate datasets as follows:
# X_train – input data used to train the model
# X_test  – input data used to test the model
# y_train – correct output used to train the model
# y_test  – correct output used to test the model
# Therefore, we use four separate variables to store the four results.
# X represents the independent variable, while y represents the dependent variable.
#70% of the data is used for learning, and 30% is used to test what the model has learned.

In [ ]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(independent, dependent, test_size=0.30, random_state=0)

In [ ]:
# We import the LinearRegression model from the sklearn library.
# We create the model and store it in a variable called "regressor".
# The fit() function trains the model using X_train and y_train.
# During training, the model calculates the weight (coefficient) and bias (intercept).
# After this step, the model has learned the relationship between experience and salary.
#The model studies the training data and learns how changes in years of experience affect salary.

In [16]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()

regressor.fit(X_train,y_train)

LinearRegression()

In [ ]:
# The message shown above is a warning, not an error, and the code can still run.

In [ ]:
# Display the weight (w) learned by the trained model.
# The weight is stored in the regressor's coef_ attribute.

In [19]:
weight=regressor.coef_
weight

array([[9360.26128619]])

In [ ]:
# Display the bias (b) learned by the trained model.
# The bias is stored in the regressor's intercept_ attribute.

In [20]:
bais=regressor.intercept_
bais

array([26777.3913412])

In [ ]:
# The trained model uses the testing input data (X_test)
# to predict the corresponding salary values.
# The predicted salaries are stored in the variable "y_pred".

#regressor — the trained linear regression model.
#.predict() — asks the trained model to make predictions.
#X_test — the years-of-experience data kept aside for testing.
#y_pred — the salaries predicted by the model.

In [21]:
y_pred=regressor.predict(X_test)

In [ ]:
#This is the model evaluation stage
# We import the r2_score function to measure the model's performance.

In [ ]:
# We compare the actual salaries (y_test) with the predicted salaries (y_pred).
# The calculated R² score is stored in the variable "r_score".

In [22]:
from sklearn.metrics import r2_score 
r_score=r2_score(y_test,y_pred)

In [ ]:
# Display the R² score.
#The R² score is close to 1, so the model performs well on the test data. 
#It is like cross-checking whether the model has learned the relationship correctly

In [23]:
r_score

0.9740993407213511

In [ ]:
# We use the pickle library to save the trained model.
# We create a filename called "finalized_model_linear.sav"
# and store it in the variable "filename".

In [ ]:
#The trained model is saved as a file named finalized_model_linear.sav. 
#We can load and reuse this model later without training it again.

In [24]:
import pickle
filename="findlized_model_linear.sav"

In [ ]:
# We save the trained model stored in "regressor" to the specified file.
# When the following code is executed, the trained model is saved as a file.
# The file will be created in the same folder where the Jupyter Notebook is running.
# It will also appear in Jupyter's file browser because both locations refer to the same folder.

In [25]:
pickle.dump(regressor,open(filename,'wb'))

In [ ]:
# We load the previously saved model from the file.
# "rb" means that the file is opened in read-binary mode.

# We give 13 years of experience to the loaded model.
# The model then predicts the expected salary.
# The predicted result is stored in the variable "result".

In [28]:
loaded_model=pickle.load(open("findlized_model_linear.sav",'rb'))
result=loaded_model.predict([[13]])

C:\Users\rousan\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [ ]:
# Display the predicted salary.
#We reopened the trained model saved earlier and asked it to predict the salary for a person with 13 years of experience. 
#The model predicted a salary of approximately 167,181.31.
#Ignore the warning and you still get the result

In [27]:
result

array([[167181.3106341]])